BEGIN;

CREATE TABLE IF NOT EXISTS archivos_media_subidos (
  nombre_archivo VARCHAR(180) PRIMARY KEY,
  id_usuario BIGINT NOT NULL REFERENCES usuarios(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
  fecha_subida TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
